//
// CodableHelper.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import SwiftyJSON

public typealias EncodeResult = (data: Data?, error: Error?)

open class CodableHelper {
    
    open class func decode<T>(_ type: T.Type, from data: Data) -> (decodableObj: T?, error: Error?) where T : Decodable {
        var returnedDecodable: T? = nil
        var returnedError: Error? = nil
        
        let decoder = JSONDecoder()
        decoder.dataDecodingStrategy = JSONDecoder.DataDecodingStrategy.base64
        if #available(iOS 10.0, *) {
            decoder.dateDecodingStrategy = JSONDecoder.DateDecodingStrategy.iso8601
        }
        
        do {
            returnedDecodable = try decoder.decode(type, from: data)
        } catch {
            returnedError = error
        }
        
        return (returnedDecodable, returnedError)
    }
    
    open class func encode<T>(_ value: T, prettyPrint: Bool = false) -> EncodeResult where T : Encodable {
        var returnedData: Data?
        var returnedError: Error? = nil
        
        let encoder = JSONEncoder()
        if #available(iOS 11.0, *) {
            encoder.outputFormatting = (prettyPrint) ? JSONEncoder.OutputFormatting.prettyPrinted : JSONEncoder.OutputFormatting.sortedKeys
        } else {
            // Fallback on earlier versions
        }
        encoder.dataEncodingStrategy = JSONEncoder.DataEncodingStrategy.base64
        if #available(iOS 10.0, *) {
            encoder.dateEncodingStrategy = .iso8601
        }
        
        do {
            returnedData = try encoder.encode(value)
        } catch {
            returnedError = error
        }
        
        return (returnedData, returnedError)
    }
    
}

