//
// ApplicationUser.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class ApplicationUser: Codable {

    public var userName: String?
    public var firstName: String?
    public var lastName: String?
    public var fullName: String?
    public var email: String?
    public var providerName: String?
    public var providerId: String?
    public var pictureUrl: String?
    public var bio: String?
    public var createdEvents: [Event]?
    public var joinedEvents: [EventGuest]?
    public var id: String?

    public init() {}

}
