//
// EventGuest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class EventGuest: Codable {

    public var eventId: Int32?
    public var event: Event?
    public var guestId: String?
    public var guest: ApplicationUser?

    public init() {}

}
