//
// Event.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Event: Codable {

    public var id: Int32?
    public var title: String?
    public var creator: ApplicationUser?
    public var startTime: Date?
    public var endTime: Date?
    public var latitude: Double?
    public var longitude: Double?
    public var eventDescription: String?
    public var host: String?
    public var locationDescription: String?
    public var eventGuests: [EventGuest]?
    public var gameId: Int32?
    public var game: Game?

    public init() {}

}
