//
// Game.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Game: Codable {

    public var id: Int32?
    public var title: String?
    public var gameDescription: String?
    public var imageUrl: String?
    public var url: String?
    public var numberOfPlayers: Int32?

    public init() {}

}
