//
// Game.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import EVReflection

open class Game: EVObject {

    public var id: Int32 = 0
    public var title: String = ""
    public var description: String = ""
    public var imageUrl: String = ""
    public var url: String = ""
    public var numberOfPlayers: Int32 = 0

    //public init() {}

}
