//
// LoginViewModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class LoginViewModel: Codable {

    public var email: String?
    public var userName: String?
    public var password: String?
    public var rememberMe: Bool?

    public init() {}

}
