//
// Event.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import EVReflection

//Converting String to date
//https://stackoverflow.com/questions/36861732/swift-convert-string-to-date

open class Event: EVObject {

     var id: Int32 = 0
     var title: String = ""
     var creator: ApplicationUser = ApplicationUser()
     var startTime: String? = ""
     var endTime: String? = ""
     var latitude: Double = 0
     var longitude: Double = 0
     var eventDescription: String = ""
     var host: String = ""
     var locationDescription: String = ""
     var eventGuests: [EventGuest] = []
     var gameId: Int32 = 0
     var game: Game = Game()

    // init() {}

}
