//
// Game.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import EVReflection

open class Game: EVObject {

    var id: Int32 = 0
    var title: String = ""
    var gameDescription: String = ""
    var imageUrl: String = ""
    var url: String = ""
    var numberOfPlayers: Int32 = 0

    //public init() {}

}
