//
// LoginViewModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import EVReflection

open class LoginViewModel: EVObject {

    public var email: String = ""
    public var password: String = ""
    public var rememberMe: Bool = false

    //public init() {}

}
